# Big-Data-Lab4

I solved the problem 
so now, the lab4 is running without issues
